services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5107:5107"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=BlogDb;Username=blogUser;Password=mypassword123
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=BlogDb
      - POSTGRES_USER=blogUser
      - POSTGRES_PASSWORD=mypassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blogUser -d BlogDb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data: